from __future__ import annotations

from .models import HarmonicSource


HARMONIC_SOURCES: list[HarmonicSource] = [
    HarmonicSource(
        name="pyharmonics",
        url="https://github.com/niall-oc/pyharmonics",
        category="license_restricted_reference",
        trustLevel="REFERENCE_ONLY_LICENSE_BLOCKED",
        useNow="API-shape comparison only; runtime adapter is disabled by default.",
        limitation="Installed 1.5.3 package contains a restrictive NOC license despite an MIT classifier; do not use without separate legal review.",
        backendRole="disabled_library_adapter_reference",
    ),
    HarmonicSource(
        name="pyharmonics docs",
        url="https://pyharmonics.readthedocs.io/en/latest/",
        category="documentation",
        trustLevel="OPEN_SOURCE_REFERENCE",
        useNow="API/reference behavior only.",
        limitation="Examples are not NSE-specific and the packaged runtime license is not accepted for core use.",
        backendRole="implementation_reference",
    ),
    HarmonicSource(
        name="HarmonicPatterns",
        url="https://github.com/djoffrey/HarmonicPatterns",
        category="open_source_library",
        trustLevel="OPEN_SOURCE_SECONDARY_REFERENCE",
        useNow="Compare completed/predicting pattern output against pyharmonics/internal validator.",
        limitation="Dependency burden and Windows install path must be checked.",
        backendRole="false_positive_comparison",
    ),
    HarmonicSource(
        name="stock-pattern",
        url="https://github.com/BennyThadikaran/stock-pattern",
        category="open_source_reference",
        trustLevel="GPL_REFERENCE_ONLY",
        useNow="Study CLI/backtest and harmonic pattern ideas.",
        limitation="GPL-3.0 license; do not copy code into core unless license is accepted.",
        backendRole="reference_only",
    ),
    HarmonicSource(
        name="TradingView open-source harmonic script",
        url="https://www.tradingview.com/script/f6Ae6av3-Auto-Harmonic-Patterns-Open-Source/",
        category="tradingview_reference",
        trustLevel="VISUAL_REFERENCE",
        useNow="Visual ratio/reference logic.",
        limitation="Not backend all-NSE scanner.",
        backendRole="visual_reference",
    ),
    HarmonicSource(
        name="Patterns Hunters",
        url="https://www.patternshunters.com/",
        category="commercial_scanner",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Study scanner, predictor, alert, and UI behavior.",
        limitation="TradingView-dependent; not all-NSE backend.",
        backendRole="ui_alert_reference",
    ),
    HarmonicSource(
        name="HarmonicPattern.com",
        url="https://harmonicpattern.com/",
        category="commercial_scanner",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Compare commercial scanner workflow across assets.",
        limitation="Paid/proprietary; NSE coverage and export/API must be verified.",
        backendRole="workflow_reference",
    ),
    HarmonicSource(
        name="TRN Trading Harmonic Patterns Scanner docs",
        url="https://trntrading.ai/docs/harmonic-patterns-scanner/introduction",
        category="tradingview_scanner",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Reference for multi-symbol table and breakout confirmation states.",
        limitation="Limited symbol count and TradingView dependency.",
        backendRole="scanner_state_reference",
    ),
    HarmonicSource(
        name="TradingView TRN Scanner",
        url="https://www.tradingview.com/script/RQxVyqjJ-Harmonic-Patterns-Scanner/",
        category="tradingview_scanner",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Reference for real-time TradingView alerts and adjustable accuracy.",
        limitation="Not suitable as backend.",
        backendRole="alert_reference",
    ),
    HarmonicSource(
        name="Morning Starr TradingView Scanner",
        url="https://www.tradingview.com/script/NFqBejRX-Harmonic-Pattern-Scanner/",
        category="tradingview_scanner",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Reference for completed and potential pattern handling.",
        limitation="TradingView plus companion indicator dependency.",
        backendRole="forming_pattern_reference",
    ),
    HarmonicSource(
        name="Trendoscope Harmonic Extreme",
        url="https://docs.trendoscope.com/harmonic-pattern-extreme/",
        category="tradingview_indicator",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Reference for settings, alerts, statistics, and multi-timeframe behavior.",
        limitation="Indicator, not all-NSE backend.",
        backendRole="settings_reference",
    ),
    HarmonicSource(
        name="Trendoscope UltimateX",
        url="https://www.tradingview.com/script/kbf6u0fV-Auto-Harmonic-Screener-UltimateX-Trendoscope/",
        category="tradingview_scanner",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Reference for recursive zigzag and tolerance settings.",
        limitation="TradingView Pine Screener limits.",
        backendRole="zigzag_tolerance_reference",
    ),
    HarmonicSource(
        name="JustTicks Harmonic Screener",
        url="https://justticks.in/harmonic-screener",
        category="india_nse_reference",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="India/NSE harmonic screener feature comparison.",
        limitation="Public page info limited; login/features must be verified.",
        backendRole="nse_feature_reference",
    ),
    HarmonicSource(
        name="ChartAlert Five-0 Scanner",
        url="https://chartalert.in/2024/04/05/bullish-five-0-harmonic-pattern-stock-screener/",
        category="india_nse_reference",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Reference for NSE Five-0 examples and confirmed/unconfirmed status columns.",
        limitation="Article/example, not full API.",
        backendRole="status_column_reference",
    ),
    HarmonicSource(
        name="ChartAlert Basic Scanner",
        url="https://chartalert.in/software/scanning/scanning-basic/",
        category="india_nse_scanner",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Reference for supported harmonic pattern list.",
        limitation="EOD focus; 30m/1h/4h coverage must be verified.",
        backendRole="pattern_coverage_reference",
    ),
    HarmonicSource(
        name="Chartink Harmonic Scanner",
        url="https://chartink.com/screener/copy-harmonic-create-5",
        category="india_scanner",
        trustLevel="SECONDARY_DISCOVERY_ONLY",
        useNow="Discovery/reference only.",
        limitation="Formula quality unknown; official/source confirmation required.",
        backendRole="discovery_only",
    ),
    HarmonicSource(
        name="Investar Harmonic Trading",
        url="https://investarindia.com/blog/harmonic-trading/",
        category="india_software",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="India/NSE auto-harmonic charting reference.",
        limitation="Intervals/export/API availability must be verified.",
        backendRole="nse_software_reference",
    ),
    HarmonicSource(
        name="Investar In-built Scans",
        url="https://investarindia.com/tour/in-built-scans",
        category="india_software",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Compare ready-made scan workflows.",
        limitation="Proprietary desktop/cloud software.",
        backendRole="workflow_reference",
    ),
    HarmonicSource(
        name="Investar stock screener software",
        url="https://investarindia.com/tour/stock-screener-software",
        category="india_software",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="NSE stock/futures screener reference.",
        limitation="Intraday support must be verified.",
        backendRole="nse_screener_reference",
    ),
    HarmonicSource(
        name="MotiveWave Scanner",
        url="https://docs.motivewave.com/user-guide/scanner",
        category="professional_software",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Professional scanner workflow reference for Gartley/XABCD/AB=CD/5-0.",
        limitation="Desktop/proprietary; NSE data integration unknown.",
        backendRole="scanner_workflow_reference",
    ),
    HarmonicSource(
        name="HarmonicTrader",
        url="https://harmonictrader.com/",
        category="commercial_method_reference",
        trustLevel="AUTHORITATIVE_METHOD_REFERENCE",
        useNow="Scott Carney harmonic-method reference.",
        limitation="Proprietary software, not backend.",
        backendRole="method_reference",
    ),
    HarmonicSource(
        name="ClickAlgo Harmonic Scanner",
        url="https://clickalgo.com/harmonic-indicator",
        category="commercial_platform_scanner",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Alert workflow reference.",
        limitation="cTrader/forex/CFD ecosystem, not NSE backend.",
        backendRole="alert_reference",
    ),
    HarmonicSource(
        name="GoCharting",
        url="https://gocharting.com/in",
        category="charting_platform",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="NSE/BSE/MCX charting/data reference.",
        limitation="Harmonic scanner not confirmed from checked page.",
        backendRole="charting_reference",
    ),
    HarmonicSource(
        name="TrendSpider",
        url="https://trendspider.com/",
        category="scanner_platform",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="Competitive UI/scanner benchmark.",
        limitation="Harmonic-specific NSE scanner not confirmed.",
        backendRole="competitive_reference",
    ),
    HarmonicSource(
        name="MarketInOut Pattern Screener",
        url="https://www.marketinout.com/stock-screener/industry.php?picker=traditional_patterns",
        category="pattern_scanner",
        trustLevel="EXTERNAL_REFERENCE",
        useNow="General chart-pattern screener benchmark.",
        limitation="Not harmonic-specific from checked page.",
        backendRole="general_pattern_reference",
    ),
]
