from __future__ import annotations

from .models import (
    CandidateType,
    CommandBar,
    MetricRow,
    PairRow,
    RadarCandidate,
    SourceHealth,
    SourceState,
    StatusGroup,
    Tone,
    TradePlan,
)


def metric(label: str, value: str, note: str) -> MetricRow:
    return MetricRow(label=label, value=value, note=note)


def pair(label: str, value: str) -> PairRow:
    return PairRow(label=label, value=value)


COMMAND_BAR = CommandBar(
    system="RESEARCH_ONLY",
    regime="UNVERIFIED",
    indiaVix="WAIT_DATA",
    safety="LOCKED_DATA",
    liquidityWindow="UNKNOWN",
    expiryMode="OFF",
    noTradeOverride="ON",
)


RADAR_CANDIDATES: list[RadarCandidate] = [
    RadarCandidate(
        symbol="COFORGE",
        type=CandidateType.STOCK,
        state="PRIORITY_RADAR",
        stateTone=Tone.GOOD,
        statusGroup=StatusGroup.READY,
        setup="Smart money + OI long build-up",
        timeframe=["30m", "1h", "1d"],
        price="INR 7,862",
        move="+1.8%",
        reason="Smart money, OI, volume, futures basis, anchors, and safety align.",
        decisionTitle="READY WITH TRIGGER",
        decisionText="Execute only at trigger with predefined stop and position size.",
        trade=TradePlan(entry="7,862", stop="7,780", target="8,120"),
        quality=86,
        metrics=[
            metric("Smart Money", "10/10", "CEO buy, FII bulk deal, AMC add"),
            metric("OI Quadrant", "LONG_BUILD_UP", "Price up + OI up, MWPL safe"),
            metric("Volume", "2.8x RVOL", "Avg trade size institutional"),
            metric("Basis", "+29 rising", "Futures premium expanding"),
            metric("Anchors", "Accepted", "Above deal price and AVWAP"),
            metric("Safety", "GREEN", "No FOMO or emotional lock"),
        ],
        proof=[
            pair("AMFI", "MF add confirmed"),
            pair("Bulk/Block", "FII premium deal"),
            pair("MWPL", "54% safe"),
            pair("SLB", "Low borrow risk"),
            pair("Harmonic", "No conflict"),
            pair("Expiry", "No distortion"),
        ],
        risk=[
            pair("Risk/share", "INR 82"),
            pair("Position", "60 shares"),
            pair("Max loss", "INR 4,920"),
            pair("R:R T2", "3.1"),
            pair("Correlation", "Clean"),
        ],
        sources=[
            pair("NSE", "GREEN"),
            pair("BSE", "GREEN"),
            pair("AMFI", "GREEN"),
            pair("SLB", "AMBER"),
            pair("SEBI", "GREEN"),
            pair("Broker", "GREEN"),
        ],
        series=[30, 34, 33, 38, 43, 41, 47, 51, 49, 55, 62, 66, 64, 72, 78, 81],
    ),
    RadarCandidate(
        symbol="TCS",
        type=CandidateType.HARMONIC,
        state="HARMONIC_PRZ_ACTIVE",
        stateTone=Tone.WARN,
        statusGroup=StatusGroup.WAIT,
        setup="1D Bullish Bat in PRZ",
        timeframe=["1h", "4h", "1d", "1w"],
        price="INR 3,846",
        move="+0.4%",
        reason="Daily PRZ aligns with weekly support, but volume and VWAP confirmation are pending.",
        decisionTitle="WAIT FOR CONFIRMATION",
        decisionText="Alert only above PRZ high with RVOL-TOD confirmation.",
        trade=TradePlan(entry="3,875", stop="3,790", target="4,120"),
        quality=68,
        metrics=[
            metric("Pattern", "Bullish Bat", "PRZ active, D point forming"),
            metric("PRZ", "3,820-3,870", "Current price inside zone"),
            metric("MTF", "1W support", "Higher timeframe supports reversal"),
            metric("Volume", "Pending", "Needs RVOL-TOD > 1.5"),
            metric("VWAP", "Pending", "Reclaim not confirmed"),
            metric("Data", "GREEN", "4H custom session labelled"),
        ],
        proof=[
            pair("Ratios", "Valid normal"),
            pair("1W", "Support aligned"),
            pair("1H", "Trigger pending"),
            pair("Volume", "Not confirmed"),
            pair("VWAP", "Pending"),
            pair("Invalidation", "3,790"),
        ],
        risk=[
            pair("Pattern risk", "Normal"),
            pair("Stop gap", "INR 85"),
            pair("Target 1", "3,980"),
            pair("Target 2", "4,120"),
            pair("Mode", "Watch"),
        ],
        sources=[
            pair("Feed", "GREEN"),
            pair("1D", "GREEN"),
            pair("1W", "GREEN"),
            pair("4H", "WARN"),
            pair("AMFI", "GREEN"),
            pair("Pattern", "GREEN"),
        ],
        series=[72, 69, 65, 61, 58, 54, 49, 45, 42, 40, 43, 44, 46, 49, 52, 55],
    ),
    RadarCandidate(
        symbol="RELIANCE",
        type=CandidateType.STOCK,
        state="WAIT_BASIS_CONFLICT",
        stateTone=Tone.WARN,
        statusGroup=StatusGroup.WAIT,
        setup="Smart money bullish, futures basis falling",
        timeframe=["30m", "1h", "1d"],
        price="INR 2,914",
        move="+0.6%",
        reason="Price and volume are positive, but futures basis is falling and AVWAP acceptance is incomplete.",
        decisionTitle="WAIT BASIS CONFLICT",
        decisionText="Do not chase until basis stabilizes and price holds above AVWAP.",
        trade=TradePlan(entry="2,928", stop="2,872", target="3,040"),
        quality=61,
        metrics=[
            metric("Smart Money", "Strong", "Block interest detected"),
            metric("OI", "LONG_BUILD_UP", "MWPL safe"),
            metric("Volume", "1.9x RVOL", "Good but not decisive"),
            metric("Basis", "Falling", "Institutional hedge risk"),
            metric("AVWAP", "Testing", "Not accepted yet"),
            metric("Safety", "GREEN", "No emotional block"),
        ],
        proof=[
            pair("OI", "Bullish"),
            pair("Basis", "Conflict"),
            pair("AVWAP", "Testing"),
            pair("Volume", "Good"),
            pair("Source", "Official"),
            pair("State", "WAIT"),
        ],
        risk=[
            pair("Risk/share", "INR 56"),
            pair("Position", "89 shares"),
            pair("Max loss", "INR 4,984"),
            pair("R:R T2", "2.0"),
            pair("Conflict", "Basis"),
        ],
        sources=[
            pair("NSE", "GREEN"),
            pair("BSE", "GREEN"),
            pair("F&O", "GREEN"),
            pair("AMFI", "AMBER"),
            pair("SLB", "GREEN"),
            pair("SEBI", "GREEN"),
        ],
        series=[44, 48, 53, 56, 61, 59, 63, 64, 66, 65, 67, 66, 68, 67, 66, 65],
    ),
    RadarCandidate(
        symbol="MCX GOLD MINI",
        type=CandidateType.MCX,
        state="PRIORITY_RADAR",
        stateTone=Tone.GOOD,
        statusGroup=StatusGroup.READY,
        setup="COMEX bull + INR stable + OI aligned",
        timeframe=["30m", "1h", "4h"],
        price="INR 68,950",
        move="+0.9%",
        reason="COMEX trend, real yields, DXY, COT, MCX OI, and premium align.",
        decisionTitle="READY ABOVE TRIGGER",
        decisionText="Use Gold Mini lot sizing. Exit if USD/INR conflict appears.",
        trade=TradePlan(entry="68,950", stop="68,640", target="69,700"),
        quality=82,
        metrics=[
            metric("COMEX", "Bullish", "Gold above ORB and 50 DMA"),
            metric("USD/INR", "Stable", "Currency leg not blocking"),
            metric("COT", "MM long up", "Week 3 trend build"),
            metric("MCX OI", "LONG_BUILD_UP", "Local and global aligned"),
            metric("Premium", "+320", "Domestic demand healthy"),
            metric("Safety", "GREEN", "No event block"),
        ],
        proof=[
            pair("COT", "Bullish"),
            pair("DXY", "Falling"),
            pair("Real Yield", "Falling"),
            pair("MCX OI", "Aligned"),
            pair("Premium", "Rising"),
            pair("Event", "Clear"),
        ],
        risk=[
            pair("Lot", "Gold Mini"),
            pair("Risk/lot", "INR 3,100"),
            pair("Max lots", "1"),
            pair("Margin", "OK"),
            pair("Key risk", "USD/INR"),
        ],
        sources=[
            pair("MCX", "GREEN"),
            pair("CFTC", "GREEN"),
            pair("WGC", "GREEN"),
            pair("FRED", "GREEN"),
            pair("USDINR", "GREEN"),
            pair("EIA", "NA"),
        ],
        series=[40, 42, 45, 44, 48, 52, 55, 58, 61, 64, 66, 68, 71, 74, 78, 80],
    ),
    RadarCandidate(
        symbol="HDFCBANK",
        type=CandidateType.STOCK,
        state="REJECT_SUPPLY",
        stateTone=Tone.BAD,
        statusGroup=StatusGroup.REJECT,
        setup="Supply overhang above anchor",
        timeframe=["1h", "1d", "1w"],
        price="INR 1,682",
        move="-0.3%",
        reason="Price is below AVWAP and supply overhang blocks clean upside.",
        decisionTitle="REJECT FOR NOW",
        decisionText="Keep in watchlist only. Needs anchor reclaim and supply absorption.",
        trade=TradePlan(entry="-", stop="-", target="-"),
        quality=38,
        metrics=[
            metric("Smart Money", "Mixed", "No strong current sponsor"),
            metric("OI", "Long unwind", "Price down + OI down"),
            metric("Volume", "Distribution", "High volume near highs"),
            metric("AVWAP", "Below", "Anchor not accepted"),
            metric("Supply", "High", "Seller not absorbed"),
            metric("Safety", "GREEN", "No user lock"),
        ],
        proof=[
            pair("Supply", "High"),
            pair("AVWAP", "Failed"),
            pair("OI", "Weak"),
            pair("Volume", "Sell pressure"),
            pair("State", "Reject"),
            pair("Next", "Wait"),
        ],
        risk=[
            pair("Trade", "Blocked"),
            pair("Reason", "Supply"),
            pair("R:R", "Invalid"),
            pair("Trigger", "Anchor reclaim"),
            pair("Mode", "Watch"),
        ],
        sources=[
            pair("NSE", "GREEN"),
            pair("BSE", "GREEN"),
            pair("AMFI", "AMBER"),
            pair("SHP", "GREEN"),
            pair("SLB", "GREEN"),
            pair("SEBI", "GREEN"),
        ],
        series=[70, 68, 66, 67, 64, 61, 60, 57, 55, 53, 51, 50, 48, 46, 45, 43],
    ),
]

# These records are visual examples only. Keep them non-executable even if an
# old example payload contains a bullish state or trade levels.
RADAR_CANDIDATES = [
    candidate.model_copy(
        update={
            "state": "WAIT_DEMO_DATA",
            "state_tone": Tone.WARN,
            "status_group": StatusGroup.WAIT,
            "reason": "Demonstration layout only; no fresh structured market evidence is attached.",
            "decision_title": "WAIT - DEMO DATA",
            "decision_text": "Do not trade. Run the stored-data research scanner or connect verified sources.",
            "trade": TradePlan(entry="-", stop="-", target="-"),
            "quality": 0,
            "metrics": [metric("Data", "DEMO_ONLY", "No market evidence attached")],
            "proof": [pair("Gate status", "NOT_EVALUATED")],
            "risk": [
                pair("Executable", "NO"),
                pair("Account", "INR 1,00,000"),
                pair("Reason", "DEMO_DATA"),
            ],
            "sources": [pair("Data authority", "NA"), pair("Freshness", "UNKNOWN")],
        }
    )
    for candidate in RADAR_CANDIDATES
]


SOURCE_HEALTH: list[SourceHealth] = [
    SourceHealth(
        name="AMFI Monthly Portfolio Disclosure",
        owner="AMFI",
        state=SourceState.GREEN,
        trustLabel="OFFICIAL_GROUND_TRUTH",
        updateFrequency="monthly",
        latestDataDate="2026-06",
        decisionUse="DII stock-level attribution",
        url="https://www.amfiindia.com/online-center/portfolio-disclosure",
        sourceKey="amfi_monthly_portfolio",
        maturityState="REGISTERED",
        gatePermission=False,
        sourceActivationReady=False,
    ),
    SourceHealth(
        name="NSE FII/DII",
        owner="NSE",
        state=SourceState.GREEN,
        trustLabel="AGGREGATE_CONTEXT",
        updateFrequency="daily",
        latestDataDate="2026-07-05",
        decisionUse="market liquidity regime",
        url="https://www.nseindia.com/reports/fii-dii",
        sourceKey="nse_fii_dii",
        maturityState="REGISTERED",
        gatePermission=False,
        sourceActivationReady=False,
    ),
    SourceHealth(
        name="NSE Participant OI",
        owner="NSE",
        state=SourceState.GREEN,
        trustLabel="AGGREGATE_CONTEXT",
        updateFrequency="daily",
        latestDataDate="2026-07-05",
        decisionUse="index/derivative regime only",
        url="https://www.nseindia.com/all-reports-derivatives",
        sourceKey="nse_participant_oi",
        maturityState="REGISTERED",
        gatePermission=False,
        sourceActivationReady=False,
    ),
    SourceHealth(
        name="NSE SLB",
        owner="NSE",
        state=SourceState.AMBER,
        trustLabel="OFFICIAL_ALERT",
        updateFrequency="daily",
        latestDataDate="2026-07-04",
        decisionUse="borrow pressure proxy",
        url="https://www.nseindia.com/static/products-services/slbs-trading",
        sourceKey="nse_slb",
        maturityState="REGISTERED",
        gatePermission=False,
        sourceActivationReady=False,
    ),
    SourceHealth(
        name="NSE Paid Data",
        owner="NSE",
        state=SourceState.RED,
        trustLabel="OFFICIAL_GROUND_TRUTH",
        updateFrequency="live",
        latestDataDate="not_configured",
        decisionUse="live intraday OHLCV feed",
        url="https://www.nseindia.com/static/market-data/real-time-data-subscription",
        sourceKey="nse_paid_data",
        maturityState="REGISTERED",
        gatePermission=False,
        sourceActivationReady=False,
    ),
]

SOURCE_HEALTH = [
    row.model_copy(
        update={
            "state": SourceState.NA,
            "latest_data_date": "UNVERIFIED_DEMO",
            "decision_use": f"{row.decision_use}; static example only",
            "gate_permission": False,
            "source_activation_ready": False,
        }
    )
    for row in SOURCE_HEALTH
]
