from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen
from uuid import uuid4

from . import storage
from .models import (
    DataTrust,
    SourceCatalogRecord,
    SourceMonitorSummary,
    SourceSnapshotRecord,
)
from .source_resolver import ResolvedFetch, resolve_and_fetch_source
from .storage import (
    get_latest_source_snapshot,
    save_source_fetch_attempts,
    list_source_snapshots,
    save_source_snapshot,
)


@dataclass(frozen=True)
class SourceDescriptor:
    key: str
    name: str
    url: str
    category: str
    authority: DataTrust
    expected_frequency: str
    decision_use: str
    parser_status: str
    freshness_required: bool
    stale_after_hours: int | None
    limitation: str


SOURCE_CATALOG: tuple[SourceDescriptor, ...] = (
    SourceDescriptor(
        "nse_trading_calendar",
        "NSE Trading Holiday Calendar",
        "https://www.nseindia.com/resources/exchange-communication-holidays",
        "exchange_calendar",
        DataTrust.OFFICIAL,
        "monthly",
        "Authoritative NSE segment holiday coverage and explicit special-session state.",
        "STRUCTURED_PARSER_BUILT_LIVE_ENDPOINT_VERIFIED_2026_07_11",
        True,
        1080,
        "Holiday names never imply a special open; only explicit session records can open a weekend.",
    ),
    SourceDescriptor(
        "nse_equity_universe",
        "NSE Equity Instrument Universe",
        "https://www.nseindia.com/static/market-data/securities-available-for-trading",
        "universe_identity",
        DataTrust.OFFICIAL,
        "daily",
        "Active NSE equity identity, series, ISIN, listing date and lot eligibility.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_07_11",
        True,
        48,
        "Direct official EQUITY_L.csv; identity input, not a trade signal.",
    ),
    SourceDescriptor(
        "nse_nifty500_constituents",
        "NSE Nifty 500 Constituents And Industry",
        "https://www.nseindia.com/static/products-services/indices-nifty500-index",
        "sector_membership",
        DataTrust.OFFICIAL,
        "event_based",
        "Official Nifty 500 constituent and industry mapping for sector context.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_07_11",
        True,
        744,
        "Constituent membership is versioned and must be joined point-in-time.",
    ),
    SourceDescriptor(
        "nse_nifty50_constituents",
        "NSE Nifty 50 Constituents And Industry",
        "https://www.nseindia.com/static/products-services/indices-nifty50-index",
        "sector_membership",
        DataTrust.OFFICIAL,
        "event_based",
        "Exact official Nifty 50 membership for benchmark and scan-universe selection.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_07_11",
        True,
        744,
        "Membership is versioned and joined point-in-time; it is not a trade signal.",
    ),
    SourceDescriptor(
        "nse_trade_to_trade",
        "NSE Trade-for-Trade Securities",
        "https://www.nseindia.com/all-reports",
        "tradability_restriction",
        DataTrust.OFFICIAL_FREE_EOD,
        "daily",
        "Delivery-only restriction derived from official NSE bhavcopy series BE/BT/IT/ST/BZ/SZ.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_08_04",
        True,
        36,
        "Hard no-intraday context; it is not a directional or positive scoring signal.",
    ),
    SourceDescriptor(
        "kite_derivatives_contract_master",
        "Kite Public Derivatives Contract Master",
        "https://api.kite.trade/instruments",
        "derivatives_contract_reference",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "daily",
        "Public NFO/BFO/MCX expiry and lot-size reference for research display.",
        "STRUCTURED_PARSER_BUILT_THIRD_PARTY_REFERENCE_2026_08_04",
        True,
        36,
        "Third-party operational reference only; cannot unlock source activation or execution readiness.",
    ),
    SourceDescriptor(
        "nse_board_meetings",
        "NSE Board Meeting Calendar",
        "https://www.nseindia.com/api/corporate-board-meetings?index=equities",
        "corporate_event_calendar",
        DataTrust.OFFICIAL,
        "intraday",
        "Upcoming board meetings and financial-results event risk by symbol.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_08_04",
        True,
        24,
        "Event context only; purpose text must explicitly mention results before setting the results flag.",
    ),
    SourceDescriptor(
        "nse_most_active_futures",
        "NSE Most-Active Futures Contracts",
        "https://www.nseindia.com/api/snapshot-derivatives-equity?index=futures",
        "derivatives_activity",
        DataTrust.OFFICIAL,
        "intraday",
        "Most-active NSE futures contracts by volume and value.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_08_04",
        True,
        2,
        "Activity and OI context only; contract activity is not independent directional confirmation.",
    ),
    SourceDescriptor(
        "nse_most_active_options",
        "NSE Most-Active Options Contracts",
        "https://www.nseindia.com/api/snapshot-derivatives-equity?index=options",
        "derivatives_activity",
        DataTrust.OFFICIAL,
        "intraday",
        "Most-active NSE options contracts by volume and value.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_08_04",
        True,
        2,
        "Option-premium change must never be represented as underlying direction.",
    ),
    SourceDescriptor(
        "nse_ipo_issue_calendar",
        "NSE IPO Issue Calendar",
        "https://www.nseindia.com/api/ipo-current-issue",
        "listing_event_calendar",
        DataTrust.OFFICIAL,
        "intraday",
        "Current and issue-calendar IPO rows with original Active, Closed or Forthcoming status.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_08_04",
        True,
        24,
        "This is an issue calendar, not the dead public-recent-listings endpoint and not a trade signal.",
    ),
    SourceDescriptor(
        "nse_pr_market_snapshot",
        "NSE PR Market Snapshot",
        "https://www.nseindia.com/all-reports",
        "market_snapshot_context",
        DataTrust.OFFICIAL_FREE_EOD,
        "daily",
        "Symbol-safe gainers, losers, 52-week events, equity corporate actions and market capitalisation.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_08_04",
        True,
        36,
        "Derived from the same PR archive as bhavcopy; never count it as independent confirmation.",
    ),
    SourceDescriptor(
        "nse_bhavcopy_eod",
        "NSE Bhavcopy / EOD Data",
        "https://www.nseindia.com/all-reports",
        "stock_eod",
        DataTrust.OFFICIAL_FREE_EOD,
        "daily",
        "Official EOD price/volume validation and historical daily candles.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_07_11",
        True,
        36,
        "Dynamic/download page; parser must verify report date and file hash.",
    ),
    SourceDescriptor(
        "nse_index_close_eod",
        "NSE All Indices Close EOD",
        "https://www.nseindia.com/reports-indices-historical-index-data",
        "market_sector_context",
        DataTrust.OFFICIAL_FREE_EOD,
        "daily",
        "Official Nifty, India VIX and sector-index history for point-in-time context.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_07_11",
        True,
        36,
        "Daily archive input; 200 stored Nifty observations are required before market context can pass.",
    ),
    SourceDescriptor(
        "nse_fii_dii",
        "NSE FII/DII Data",
        "https://www.nseindia.com/reports/fii-dii",
        "institutional_flow",
        DataTrust.OFFICIAL,
        "daily",
        "Aggregate cash-market institutional regime context.",
        "OFFICIAL_API_STRUCTURED_PARSER",
        True,
        36,
        "Aggregate market-level flow, not stock-level attribution.",
    ),
    SourceDescriptor(
        "nsdl_fpi_daily",
        "NSDL Daily FPI Investment Trends",
        "https://fpi.nsdl.co.in/web/Reports/Latest.aspx",
        "institutional_flow",
        DataTrust.OFFICIAL,
        "daily",
        "Aggregate cash, debt, and derivatives FPI regime context.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_07_13",
        True,
        48,
        "Aggregate daily trends only; this source cannot prove stock-level FPI holdings or intraday sponsorship.",
    ),
    SourceDescriptor(
        "nsdl_fpi_fortnightly",
        "NSDL Fortnightly FPI Sector Context",
        "https://fpi.nsdl.co.in/web/Reports/FPIFortnightlySelection.aspx",
        "institutional_flow",
        DataTrust.OFFICIAL,
        "fortnightly",
        "Aggregate sector-level FPI investment context when the report table is published.",
        "STRUCTURED_PARSER_BUILT_ACCESS_SENSITIVE_2026_08_01",
        True,
        360,
        "Sector-level only; cannot prove stock-level FII buying. Selection pages and WAF rejections yield empty parse.",
    ),
    SourceDescriptor(
        "cdsl_fpi_fortnightly_sector",
        "CDSL Fortnightly Sector-wise FPI AUC",
        "https://www.cdslindia.com/Publications/ForeignPortInvestor.html",
        "institutional_flow",
        DataTrust.OFFICIAL,
        "fortnightly",
        "Sector-level FPI AUC and net investment from CDSL public fortnightly HTML reports.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_08_01",
        True,
        360,
        "Sector aggregate only; not stock-level FII buying. Use as companion when NSDL fortnightly selection is WAF-blocked.",
    ),
    SourceDescriptor(
        "nse_participant_oi",
        "NSE Participant OI Reports",
        "https://www.nseindia.com/all-reports-derivatives",
        "derivatives_regime",
        DataTrust.OFFICIAL,
        "daily",
        "FII/DII/Pro/Client derivative positioning context; index/regime use.",
        "STRUCTURED_PARSER_BUILT_SCOPE_LIMITED",
        True,
        36,
        "Participant OI is not stock-level FII buying.",
    ),
    SourceDescriptor(
        "nse_option_chain",
        "NSE Equity Option Chain Monitor",
        "https://www.nseindia.com/option-chain",
        "derivatives_intraday_context",
        DataTrust.OFFICIAL,
        "intraday",
        "Current CE/PE OI, volume and exchange IV when the endpoint publishes data.",
        "ENDPOINT_MONITORED_FAIL_CLOSED",
        True,
        2,
        "An empty response is NO_DATA_NOW and cannot confirm a derivative gate.",
    ),
    SourceDescriptor(
        "nse_oi_spurts",
        "NSE OI Spurts",
        "https://www.nseindia.com/market-data/oi-spurts",
        "derivatives_intraday_context",
        DataTrust.OFFICIAL,
        "intraday",
        "Current stock-level futures OI change and activity context.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_07_13",
        True,
        2,
        "OI spurts contain no MWPL denominator; they cannot calculate MWPL utilization or independently unlock G13.",
    ),
    SourceDescriptor(
        "nse_pit_current",
        "NSE Current PIT Disclosures",
        "https://www.nseindia.com/companies-listing/corporate-filings-insider-trading",
        "regulatory_filings",
        DataTrust.OFFICIAL,
        "daily",
        "Current NSE insider-disclosure rows when published.",
        "ENDPOINT_MONITORED_FAIL_CLOSED",
        True,
        48,
        "An empty current report is shown as NO_DATA_NOW, not evidence of no insider activity historically.",
    ),
    SourceDescriptor(
        "nse_pledge_data",
        "NSE Promoter Pledge Data",
        "https://www.nseindia.com/companies-listing/corporate-filings-pledged-data",
        "promoter_risk",
        DataTrust.OFFICIAL,
        "quarterly",
        "Delayed promoter pledge concentration and change-risk context.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_07_13",
        True,
        2880,
        "The endpoint is company-name based; point-in-time symbol/ISIN mapping is required before stock-level scoring.",
    ),
    SourceDescriptor(
        "bse_pledge_data",
        "BSE Consolidated Promoter Pledge Shareholding",
        "https://www.bseindia.com/corporates/Pledge_new",
        "promoter_risk",
        DataTrust.OFFICIAL,
        "quarterly",
        "BSE company-level promoter pledge and encumbrance concentration for delayed risk flags.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_08_01",
        True,
        2880,
        "Scrip-code based; NSE symbol mapping required before stock-level scoring. Large JSON may time out without raised timeout/seed.",
    ),
    SourceDescriptor(
        "nse_regulation_29",
        "NSE Regulation 29 Acquisition And Disposal Disclosures",
        "https://www.nseindia.com/companies-listing/corporate-filings-regulation-29",
        "smart_money_ownership",
        DataTrust.OFFICIAL,
        "event_based",
        "Official Regulation 29 promoter acquisition and disposal event rows when published.",
        "STRUCTURED_PARSER_BUILT_EMPTY_OFFICIAL_ENDPOINT_2026_08_01",
        True,
        72,
        "Official endpoint may legitimately return an empty list when no Reg-29 events are present.",
    ),
    SourceDescriptor(
        "nse_regulation_31",
        "NSE Regulation 31 Promoter Encumbrance Disclosures",
        "https://www.nseindia.com/companies-listing/corporate-filings-regulation-31",
        "promoter_risk",
        DataTrust.OFFICIAL,
        "event_based",
        "Official Regulation 31 encumbrance create/release/invoke event rows when published.",
        "STRUCTURED_PARSER_BUILT_EMPTY_OFFICIAL_ENDPOINT_2026_08_01",
        True,
        72,
        "Official endpoint may legitimately return an empty list when no Reg-31 events are present.",
    ),
    SourceDescriptor(
        "nse_block_deal_live",
        "NSE Live Block-Deal Market Summary",
        "https://www.nseindia.com/api/block-deal",
        "market_activity_context",
        DataTrust.OFFICIAL,
        "intraday",
        "Current block-deal session activity and traded-value context.",
        "STRUCTURED_CONTEXT_PARSER",
        True,
        24,
        "Market summary lacks named counterparties and cannot prove a smart-money sponsor.",
    ),
    SourceDescriptor(
        "bse_bhavcopy_eod",
        "BSE Equity Bhavcopy EOD Monitor",
        "https://www.bseindia.com/markets/MarketInfo/BhavCopy.aspx",
        "eod_price_volume_backup",
        DataTrust.OFFICIAL_FREE_EOD,
        "daily",
        "BSE EOD OHLCV backup when an official ZIP is published.",
        "ENDPOINT_MONITORED_FAIL_CLOSED",
        True,
        36,
        "HTML responses are retained and shown as NO_DATA_NOW; only a schema-valid ZIP is usable.",
    ),
    SourceDescriptor(
        "nse_fno_ban",
        "NSE F&O Ban List",
        "https://nsearchives.nseindia.com/content/fo/fo_secban.csv",
        "derivatives_safety",
        DataTrust.OFFICIAL,
        "daily",
        "Hard veto for symbols in the official dated F&O ban artifact.",
        "STRUCTURED_PARSER_LIVE_VERIFIED_2026_07_11",
        True,
        36,
        "Ban membership does not contain or imply symbol-level MWPL utilization.",
    ),
    SourceDescriptor(
        "nse_mto_delivery",
        "NSE MTO Security-wise Delivery",
        "https://archives.nseindia.com/archives/equities/mto/MTO_{ddmmyyyy}.DAT",
        "delivery_volume",
        DataTrust.OFFICIAL,
        "daily",
        "Cash-market deliverable quantity and delivery percentage by symbol.",
        "STRUCTURED_PARSER_PHASE1_30PACK",
        True,
        36,
        "Record type 20 rows only; prefer EQ series in screener extractors.",
    ),
    SourceDescriptor(
        "nse_short_selling",
        "NSE Daily Short Selling Disclosure",
        "https://archives.nseindia.com/archives/equities/shortSelling/shortselling_{ddmmyyyy}.csv",
        "short_interest",
        DataTrust.OFFICIAL,
        "daily",
        "Daily disclosed short quantity by security.",
        "STRUCTURED_PARSER_PHASE1_30PACK",
        True,
        36,
        "Filename is lowercase shortselling_DDMMYYYY.csv.",
    ),
    SourceDescriptor(
        "nse_preopen_cash",
        "NSE Cash Pre-Open Market",
        "https://www.nseindia.com/api/market-data-pre-open?key=ALL",
        "preopen_auction",
        DataTrust.OFFICIAL,
        "intraday",
        "Cash pre-open IEP, imbalance and turnover by symbol.",
        "STRUCTURED_PARSER_PHASE1_30PACK",
        True,
        12,
        "Distinct from nse_preopen_fo; requires NSE session cookies when fetched live.",
    ),
    SourceDescriptor(
        "bse_fo_bhavcopy",
        "BSE Derivatives F&O Bhavcopy",
        "https://www.bseindia.com/download/BhavCopy/Derivative/BhavCopy_BSE_FO_0_0_0_{yyyymmdd}_F_0000.CSV",
        "eod_derivatives_price_oi",
        DataTrust.OFFICIAL_FREE_EOD,
        "daily",
        "BSE FO end-of-day prices and open interest in the unified FO CSV format.",
        "STRUCTURED_PARSER_PHASE1_30PACK",
        True,
        36,
        "Not the cash equity bhavcopy; old zip format is retired.",
    ),
    SourceDescriptor(
        "bse_insider_trading",
        "BSE Insider Trading Disclosures",
        "https://api.bseindia.com/BseIndiaAPI/api/getCorp_Regulation_ng/w?Isdefault=1",
        "insider_disclosure",
        DataTrust.OFFICIAL,
        "daily",
        "SEBI PIT Regulation insider filings via BSE corporate API.",
        "STRUCTURED_PARSER_PHASE2_30PACK",
        True,
        48,
        "Default latest window; symbol-specific fan-out is optional later.",
    ),
    SourceDescriptor(
        "nse_option_chain_nifty",
        "NSE Nifty Option Chain",
        "https://www.nseindia.com/api/option-chain-equities?symbol=NIFTY",
        "index_option_chain",
        DataTrust.OFFICIAL,
        "intraday",
        "Nifty option chain strikes with OI/IV/LTP context.",
        "STRUCTURED_PARSER_PHASE2_30PACK",
        True,
        12,
        "Requires NSE cookies; v3 Indices expiry resolution is a later enhancement.",
    ),
    SourceDescriptor(
        "nse_option_chain_banknifty",
        "NSE BankNifty Option Chain",
        "https://www.nseindia.com/api/option-chain-equities?symbol=BANKNIFTY",
        "index_option_chain",
        DataTrust.OFFICIAL,
        "intraday",
        "BankNifty option chain strikes with OI/IV/LTP context.",
        "STRUCTURED_PARSER_PHASE2_30PACK",
        True,
        12,
        "Requires NSE cookies.",
    ),
    SourceDescriptor(
        "lbma_gold_silver_fix",
        "LBMA Gold/Silver Fixings",
        "https://prices.lbma.org.uk/json/gold_pm.json",
        "macro_metal_benchmark",
        DataTrust.OFFICIAL,
        "daily",
        "LBMA daily gold/silver fix JSON (USD/GBP/EUR).",
        "STRUCTURED_PARSER_PHASE2_30PACK",
        True,
        48,
        "Commercial redistribution may need a licence; fine for private research.",
    ),
    SourceDescriptor(
        "eia_natgas_storage",
        "EIA Weekly Natural Gas Storage",
        "https://ir.eia.gov/ngs/wngsr.csv",
        "macro_energy",
        DataTrust.OFFICIAL,
        "weekly",
        "Weekly US natural gas storage by region (wngsr.csv, no API key).",
        "STRUCTURED_PARSER_PHASE2_30PACK",
        True,
        168,
        "Distinct from eia_weekly_petroleum_stocks already in registry.",
    ),
    SourceDescriptor(
        "usda_wasde_cornell",
        "USDA WASDE Official XML",
        "https://esmis.nal.usda.gov/api/v1/release/findByIdentifier/WASDE",
        "macro_agriculture",
        DataTrust.OFFICIAL,
        "monthly",
        "ESMIS release discovery and full official attribute-based WASDE XML values.",
        "STRUCTURED_OFFICIAL_XML_ENHANCED_PACK4_2026_08_10",
        True,
        720,
        "ESMIS discovery -> official XML -> USDA month walk-back -> Cornell text fallback; commodity context only and zero-score.",
    ),
    SourceDescriptor(
        "rbi_fbil_usdinr",
        "RBI/FBIL USDINR Reference Archive",
        "https://www.rbi.org.in/scripts/ReferenceRateArchive.aspx",
        "macro_fx",
        DataTrust.OFFICIAL,
        "daily",
        "Official FBIL USD/INR via RBI archive multi-step form POST.",
        "STRUCTURED_PARSER_PHASE3_MULTISTEP",
        True,
        48,
        "GET form + POST date range; empty form shell must not wipe last good.",
    ),
    SourceDescriptor(
        "nse_fii_derivatives_stats",
        "NSE FII Derivatives Statistics",
        "https://archives.nseindia.com/content/fo/fii_stats_{dd-Mon-YYYY}.xls",
        "derivatives_flow",
        DataTrust.OFFICIAL,
        "daily",
        "FII index/stock futures and options buy/sell and OI statistics.",
        "STRUCTURED_PARSER_PHASE2_30PACK",
        True,
        36,
        "XLS parsed with xlrd when available.",
    ),
    SourceDescriptor(
        "nse_index_option_chain_v3",
        "NSE Index Option Chain v3 NIFTY",
        "https://www.nseindia.com/api/option-chain-v3?type=Indices&symbol=NIFTY",
        "index_option_chain",
        DataTrust.OFFICIAL,
        "intraday",
        "Index option-chain-v3 with nearest expiry resolved from contract-info.",
        "STRUCTURED_PARSER_PHASE3_MULTISTEP",
        True,
        12,
        "Requires NSE cookies; multi-step expiry resolution.",
    ),

    SourceDescriptor(
        "yahoo_cme_proxy",
        "Yahoo CME futures proxy OHLC",
        "https://query1.finance.yahoo.com/v8/finance/chart/GC=F",
        "finish_30_pack",
        DataTrust.OFFICIAL,
        "daily",
        "Yahoo CME futures proxy OHLC",
        "STRUCTURED_PARSER_FINISH_30",
        True,
        48,
        "Finish-set source for complete 30-pack coverage.",
    ),
    SourceDescriptor(
        "yahoo_lme_proxy",
        "Yahoo LME/base-metal futures proxy OHLC",
        "https://query1.finance.yahoo.com/v8/finance/chart/ALI=F",
        "finish_30_pack",
        DataTrust.OFFICIAL,
        "daily",
        "Yahoo LME/base-metal futures proxy OHLC",
        "STRUCTURED_PARSER_FINISH_30",
        True,
        48,
        "Finish-set source for complete 30-pack coverage.",
    ),
    SourceDescriptor(
        "mcx_top_participants",
        "MCX Top Participants / Market-wide OI",
        "https://www.mcxindia.com/market-data/top-participants",
        "finish_30_pack",
        DataTrust.OFFICIAL,
        "daily",
        "MCX Top Participants / Market-wide OI",
        "STRUCTURED_PARSER_FINISH_30",
        True,
        48,
        "Finish-set source for complete 30-pack coverage.",
    ),
    SourceDescriptor(
        "mcx_warehouse_stocks",
        "MCX Warehouse / delivery proxy",
        "https://www.mcxindia.com/market-operations/clearing-settlement/delivery-reports",
        "finish_30_pack",
        DataTrust.OFFICIAL,
        "daily",
        "MCX Warehouse / delivery proxy",
        "STRUCTURED_PARSER_FINISH_30",
        True,
        48,
        "Finish-set source for complete 30-pack coverage.",
    ),
    SourceDescriptor(
        "ncdex_bhavcopy",
        "NCDEX live futures / bhav page",
        "https://www.ncdex.com/market-data/live-futures-prices",
        "finish_30_pack",
        DataTrust.OFFICIAL,
        "daily",
        "NCDEX live futures / bhav page",
        "STRUCTURED_PARSER_FINISH_30",
        True,
        48,
        "Finish-set source for complete 30-pack coverage.",
    ),
    SourceDescriptor(
        "amfi_portfolio_disclosure",
        "AMFI Portfolio Disclosure directory",
        "https://www.amfiindia.com/online-center/portfolio-disclosure",
        "finish_30_pack",
        DataTrust.OFFICIAL,
        "daily",
        "AMFI Portfolio Disclosure directory",
        "STRUCTURED_PARSER_FINISH_30",
        True,
        48,
        "Finish-set source for complete 30-pack coverage.",
    ),
    SourceDescriptor(
        "nse_bulk_deals_today_csv",
        "NSE Bulk Deals Daily CSV",
        "https://archives.nseindia.com/content/equities/bulk.csv",
        "finish_30_pack",
        DataTrust.OFFICIAL,
        "daily",
        "NSE Bulk Deals Daily CSV",
        "STRUCTURED_PARSER_FINISH_30",
        True,
        48,
        "Finish-set source for complete 30-pack coverage.",
    ),
    SourceDescriptor(
        "nse_bulk_deal_symbol",
        "NSE Bulk Deal Archives by Symbol (RELIANCE sample)",
        "https://www.nseindia.com/api/bulk-deal-archives?symbol=RELIANCE",
        "finish_30_pack",
        DataTrust.OFFICIAL,
        "daily",
        "NSE Bulk Deal Archives by Symbol (RELIANCE sample)",
        "STRUCTURED_PARSER_FINISH_30",
        True,
        48,
        "Finish-set source for complete 30-pack coverage.",
    ),
    SourceDescriptor(
        "nse_quote_equity_trade_info",
        "NSE Equity Trade Info delivery (RELIANCE sample)",
        "https://www.nseindia.com/api/quote-equity?symbol=RELIANCE&section=trade_info",
        "finish_30_pack",
        DataTrust.OFFICIAL,
        "daily",
        "NSE Equity Trade Info delivery (RELIANCE sample)",
        "STRUCTURED_PARSER_FINISH_30",
        True,
        48,
        "Finish-set source for complete 30-pack coverage.",
    ),
    SourceDescriptor(
        "nse_mwpl_percentages",
        "NSE Symbol-Level MWPL Percentages",
        "https://www.nseindia.com/all-reports-derivatives",
        "derivatives_safety",
        DataTrust.OFFICIAL,
        "daily",
        "Near-MWPL warning and OI-reliability gate from NCL combined (market-wide) OI.",
        "COMBINEOI_NCL_MWPL_ZIP_V1",
        True,
        36,
        "Utilization is FutEq OI / MWPL from combineoi_DDMMYYYY.zip. Ban membership still comes from fo_secban, not this file.",
    ),
    SourceDescriptor(
        "nse_asm",
        "NSE Additional Surveillance Measure",
        "https://www.nseindia.com/reports/asm",
        "stock_safety",
        DataTrust.OFFICIAL,
        "daily",
        "Hard safety veto for securities under long-term or short-term ASM surveillance.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_07_13",
        True,
        48,
        "A valid dated empty list passes the source check; a listed symbol remains blocked from READY.",
    ),
    SourceDescriptor(
        "nse_gsm",
        "NSE Graded Surveillance Measure",
        "https://www.nseindia.com/reports/gsm",
        "stock_safety",
        DataTrust.OFFICIAL,
        "daily",
        "Hard safety veto for securities currently under GSM surveillance.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_07_13",
        True,
        48,
        "A valid dated empty list means no listed securities now; it is not a fetch or parser failure.",
    ),
    SourceDescriptor(
        "nse_esm",
        "NSE Enhanced Surveillance Measure",
        "https://www.nseindia.com/reports/esm",
        "stock_safety",
        DataTrust.OFFICIAL,
        "weekly_or_change",
        "Hard safety veto for securities currently under ESM surveillance.",
        "STRUCTURED_PARSER_BUILT_LIVE_ENDPOINT_VERIFIED_2026_09_03",
        True,
        192,
        "A schema-valid empty list is distinct from a blocked, malformed or stale endpoint.",
    ),
    SourceDescriptor(
        "nse_price_bands",
        "NSE Complete Price-Band Classification",
        "https://www.nseindia.com/all-reports",
        "tradability_restriction",
        DataTrust.OFFICIAL_FREE_EOD,
        "daily",
        "Per-symbol exchange price-band class used by the tradability gate.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_09_03",
        True,
        48,
        "The file proves band percentage, not today's exact rounded lower/upper boundary; missing exact geometry remains WAIT.",
    ),
    SourceDescriptor(
        "nse_auction_securities",
        "NSE Periodic Call Auction Illiquid Securities",
        "https://www.nseindia.com/static/regulations/periodic-call-auction-illiquid-securities",
        "tradability_restriction",
        DataTrust.OFFICIAL,
        "quarterly_or_change",
        "Current membership gate for illiquid securities traded through periodic call auction.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_09_03",
        True,
        2232,
        "Only the official periodic-call-auction list is accepted; settlement-auction and SLB files are excluded.",
    ),
    SourceDescriptor(
        "nse_slb",
        "NSE SLB Reports",
        "https://www.nseindia.com/static/products-services/slbs-trading",
        "borrow_pressure",
        DataTrust.OFFICIAL,
        "daily",
        "Borrow/lending proxy for short pressure and squeeze risk.",
        "STRUCTURED_OPEN_POSITION_ARTIFACT_LIVE_VERIFIED_2026_07_13",
        True,
        36,
        "Official outstanding borrowed quantity by symbol; no borrow yield in this artifact, and not a clean stock-wise short-interest report.",
    ),
    SourceDescriptor(
        "nse_fo_bhavcopy",
        "NSE F&O UDiFF Bhavcopy",
        "https://www.nseindia.com/all-reports-derivatives",
        "stock_derivatives_eod",
        DataTrust.OFFICIAL_FREE_EOD,
        "daily",
        "Stock futures/options EOD price, OI, OI change, basis, and contract context.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_07_11",
        False,
        36,
        "EOD only; synchronized live IV/Greeks still require verified live quotes.",
    ),
    SourceDescriptor(
        "nse_large_deals",
        "NSE Bulk / Block / Large Deals",
        "https://www.nseindia.com/market-data/large-deals",
        "smart_money_events",
        DataTrust.OFFICIAL,
        "daily",
        "Deal price anchors, institutional accumulation/distribution events.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_07_11",
        True,
        36,
        "Must distinguish bulk, block, and large deal context before scoring.",
    ),
    SourceDescriptor(
        "nse_large_deals_snapshot",
        "NSE Live Large Deals Snapshot (Bulk/Block/Short)",
        "https://www.nseindia.com/api/snapshot-capital-market-largedeal",
        "smart_money_events",
        DataTrust.OFFICIAL,
        "intraday",
        "Named bulk/block deal anchors with client, side, quantity and WATP.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_08_01",
        True,
        36,
        "Companion for empty live /api/block-deal session payload; still requires symbol mapping for radar use.",
    ),
    SourceDescriptor(
        "nse_corporate_filings_actions",
        "NSE Corporate Filings / Actions",
        "https://www.nseindia.com/companies-listing/corporate-filings-actions",
        "corporate_actions",
        DataTrust.OFFICIAL,
        "daily",
        "Adjust price/volume/holdings for splits, bonus, rights, mergers, actions.",
        "STRUCTURED_PARSER_LIVE_VERIFIED_2026_07_11",
        True,
        36,
        "Verified official JSON snapshot; complex reconstruction terms still require event-level validation.",
    ),
    SourceDescriptor(
        "nse_daily_buyback",
        "NSE Corporate Filings Daily Buyback",
        "https://www.nseindia.com/companies-listing/corporate-filings-daily-buy-back",
        "buyback",
        DataTrust.OFFICIAL,
        "daily",
        "Open-market buyback execution and support/float reduction context.",
        "STRUCTURED_PARSER_LIVE_VERIFIED_2026_07_11",
        True,
        36,
        "Buyback quantity/value must be checked against approved size and price.",
    ),
    SourceDescriptor(
        "bse_buyback_tender",
        "BSE Buyback Tender Offer",
        "https://www.bseindia.com/markets/PublicIssues/FIS_BuybackTenderoffer.aspx",
        "buyback",
        DataTrust.OFFICIAL,
        "daily",
        "Tender buyback events and price-anchor context.",
        "INDEX_AND_XBRL_DETAIL_LIVE_VERIFIED_2026_07_11",
        True,
        48,
        "Official index and linked XBRL terms verified; event context cannot create READY by itself.",
    ),
    SourceDescriptor(
        "bse_takeover_open_offer",
        "BSE Takeover / Open Offer",
        "https://www.bseindia.com/markets/publicissues/fis_takeover",
        "control_change",
        DataTrust.OFFICIAL,
        "daily",
        "SAST/open-offer control-change and floor-price context.",
        "INDEX_AND_XBRL_DETAIL_LIVE_VERIFIED_2026_07_11",
        True,
        48,
        "Official index and linked pre/post XBRL verified; control-change context is not execution authority.",
    ),
    SourceDescriptor(
        "amfi_monthly_portfolio",
        "AMFI Monthly Portfolio Disclosure",
        "https://www.amfiindia.com/online-center/portfolio-disclosure",
        "dii_stock_level",
        DataTrust.OFFICIAL,
        "monthly",
        "Ground-truth stock-level mutual fund holdings and DII attribution.",
        "STRUCTURED_PARSER_BUILT_SCOPE_LIMITED",
        True,
        744,
        "Monthly lag; confirms swing sponsorship, not intraday flow.",
    ),
    SourceDescriptor(
        "amfi_nav",
        "AMFI All-Scheme Daily NAV",
        "https://www.amfiindia.com/spages/NAVAll.txt",
        "fund_pricing_reference",
        DataTrust.OFFICIAL,
        "daily",
        "Official scheme NAV reference and mutual-fund price history.",
        "OFFICIAL_TEXT_STRUCTURED_PARSER",
        True,
        72,
        "NAV movement cannot prove mutual-fund stock buying or selling.",
    ),
    SourceDescriptor(
        "amfi_scheme_wise",
        "AMFI Scheme-wise Disclosure",
        "https://www.amfiindia.com/otherdata/scheme-wise-disclosure",
        "dii_stock_level",
        DataTrust.OFFICIAL,
        "quarterly",
        "Quarterly scheme exposures for delayed mutual-fund sponsorship breadth.",
        "OFFICIAL_API_RESOLVER_AND_STRUCTURED_PARSER",
        True,
        2880,
        "Market value and portfolio percentage only; no quantity or intraday inference.",
    ),
    SourceDescriptor(
        "sebi_pit_sast",
        "SEBI PIT / SAST / FPI Pages",
        "https://www.sebi.gov.in/sebiweb/home/HomeAction.do?doListing=yes&sid=3&ssid=15&smid=0",
        "regulatory_filings",
        DataTrust.OFFICIAL,
        "daily",
        "Insider, takeover, pledge, and FPI disclosure context.",
        "STRUCTURED_PARSER_BUILT_LIVE_UNVERIFIED",
        True,
        48,
        "Search/results pages require strict filing-type classification.",
    ),
    SourceDescriptor(
        "rbi_fpi_monitoring",
        "RBI FPI Monitoring",
        "https://www.rbi.org.in/Scripts/BS_FiiUSer.aspx",
        "ownership_limits",
        DataTrust.OFFICIAL,
        "event_based",
        "FPI cap/caution/ban threshold context for constrained foreign buying.",
        "PLANNED",
        True,
        168,
        "Relevant only when ownership limits constrain new FPI buying.",
    ),
    SourceDescriptor(
        "mca_master_data",
        "MCA Master Data",
        "https://www.mca.gov.in/content/mca/global/en/mca/master-data/MDS.html",
        "company_registry",
        DataTrust.OFFICIAL,
        "event_based",
        "Company master data, charges, and hidden ownership clues where available.",
        "PLANNED",
        False,
        720,
        "Form-based and slower; lower priority than exchange filings.",
    ),
    SourceDescriptor(
        "mcx_bhavcopy",
        "MCX Bhavcopy / EOD Data",
        "https://www.mcxindia.com/market-data/bhavcopy",
        "mcx_eod",
        DataTrust.OFFICIAL_FREE_EOD,
        "daily",
        "Official MCX EOD price, volume, and OI confirmation.",
        "STRUCTURED_EMBEDDED_FUTURES_ARTIFACT_LIVE_VERIFIED_2026_07_13",
        True,
        36,
        "Official embedded EOD futures rows only; options, IV/Greeks and live intraday MCX still need separate verified contracts.",
    ),
    SourceDescriptor(
        "usd_inr",
        "USD/INR Live Translation Leg",
        "OPENALGO_PENDING",
        "mcx_currency_leg",
        DataTrust.OFFICIAL_OR_LICENSED,
        "live",
        "Mandatory currency translation and conflict check for MCX commodities.",
        "PENDING_VERIFIED_LIVE_DATA",
        True,
        1,
        "No executable MCX READY until a verified synchronized USD/INR feed is connected.",
    ),
    SourceDescriptor(
        "world_gold_council_oi",
        "World Gold Council Gold Open Interest",
        "https://www.gold.org/goldhub/data/gold-open-interest",
        "mcx_global_gold",
        DataTrust.OFFICIAL,
        "weekly",
        "COMEX gold OI context for MCX gold regime.",
        "STRUCTURED_DIRECT_JSON_CONTRACT_VERIFIED_2026_07_13",
        True,
        192,
        "Weekly delayed US$bn venue context; not an independent vote from CFTC and never an intraday trigger.",
    ),
    SourceDescriptor(
        "wgc_gold_etf_holdings",
        "World Gold Council ETF Holdings",
        "https://www.gold.org/goldhub/data/gold-etfs-holdings-and-flows",
        "mcx_global_gold",
        DataTrust.OFFICIAL,
        "weekly",
        "Regional physically-backed gold ETF holdings and global derived total.",
        "STRUCTURED_DIRECT_JSON_CONTRACT_VERIFIED_2026_07_13",
        True,
        240,
        "Delayed institutional-demand context; it cannot identify intraday buyers or independently unlock READY.",
    ),
    SourceDescriptor(
        "wgc_gold_etf_flows",
        "World Gold Council ETF Flows",
        "https://www.gold.org/goldhub/data/gold-etfs-holdings-and-flows",
        "mcx_global_gold",
        DataTrust.OFFICIAL,
        "weekly",
        "Regional physically-backed gold ETF flow context by tonnes.",
        "STRUCTURED_DIRECT_JSON_CONTRACT_VERIFIED_2026_07_13",
        True,
        240,
        "Delayed demand context; correlated with WGC holdings and must not be double-counted as independent proof.",
    ),
    SourceDescriptor(
        "sge_daily_report",
        "Shanghai Gold Exchange Daily Report",
        "https://en.sge.com.cn/h5_data_DailyReport",
        "mcx_global_gold",
        DataTrust.OFFICIAL,
        "daily",
        "China physical-market OHLC, volume, OI, direction and delivery-volume context.",
        "STRUCTURED_SERVER_HTML_CONTRACT_VERIFIED_2026_07_13",
        True,
        72,
        "CNY/gram delayed context. SGE premium still requires synchronized global gold, FX, units and tax treatment.",
    ),
    SourceDescriptor(
        "tradingeconomics_bdi",
        "Trading Economics Baltic Dry Index",
        "https://tradingeconomics.com/commodity/baltic",
        "global_shipping_regime",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "daily",
        "Third-party Baltic Dry Index observation for aggregate shipping-regime research context.",
        "STRUCTURED_THIRD_PARTY_PAGE_LIVE_VERIFIED_2026_08_10",
        True,
        96,
        "Third-party page, not a Baltic Exchange licensed feed; informational only and never a stock voter or score term.",
    ),
    SourceDescriptor(
        "yahoo_bdry_shipping_proxy",
        "Yahoo BDRY Shipping ETF Proxy",
        "https://query1.finance.yahoo.com/v8/finance/chart/BDRY?range=1y&interval=1d",
        "global_shipping_regime",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "daily",
        "BDRY ETF OHLCV history as a dry-bulk shipping sentiment proxy.",
        "STRUCTURED_THIRD_PARTY_PROXY_LIVE_VERIFIED_2026_08_10",
        True,
        96,
        "BDRY is an ETF proxy, never the Baltic Dry Index; informational only and zero-score.",
    ),
    SourceDescriptor(
        "google_trends_india_rss",
        "Google Trends India RSS",
        "https://trends.google.com/trending/rss?geo=IN",
        "aggregate_search_interest",
        DataTrust.OFFICIAL,
        "intraday",
        "Current India trending topics and approximate traffic for broad research context.",
        "STRUCTURED_OFFICIAL_RSS_LIVE_VERIFIED_2026_08_10",
        True,
        6,
        "Top-topic RSS is not arbitrary keyword history, stock-level evidence, a Consensus vote, or a Screener score term.",
    ),
    SourceDescriptor(
        "google_news_rss",
        "Google News India Equity RSS",
        "https://news.google.com/rss/search?q=Indian%20stock%20market%20NSE%20BSE&hl=en-IN&gl=IN&ceid=IN:en",
        "news_context",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "intraday",
        "Fresh headlines from five bounded India-equity Google News RSS searches.",
        "STRUCTURED_PUBLIC_RSS_LIVE_ROUTE_VERIFIED_2026_08_10",
        True,
        24,
        "Aggregated publisher headlines; seven-day age gate, no fuzzy ticker mapping, informational only and zero-score.",
    ),
    SourceDescriptor(
        "angelone_instrument_master",
        "Angel One Public Instrument Master",
        "https://margincalculator.angelone.in/OpenAPI_File/files/OpenAPIScripMaster.json",
        "broker_instrument_reference",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "daily",
        "Public broker token and contract reference master with lot/freeze/CAS controls.",
        "STRUCTURED_PUBLIC_MASTER_LIVE_VERIFIED_2026_08_10",
        True,
        48,
        "Catalog/parameter identity only; not a quote source, voter, score term or broker authorization.",
    ),
    SourceDescriptor(
        "dhan_instrument_master",
        "Dhan Public Detailed Instrument Master",
        "https://images.dhan.co/api-data/api-scrip-master-detailed.csv",
        "broker_instrument_reference",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "daily",
        "Public security IDs and instrument controls including surveillance and broker limits.",
        "STRUCTURED_PUBLIC_MASTER_LIVE_VERIFIED_2026_08_10",
        True,
        48,
        "Catalog/reference only; expired and out-of-scope contracts are excluded from normalized output; zero-score.",
    ),
    SourceDescriptor(
        "nse_market_status",
        "NSE Market Session Status",
        "https://www.nseindia.com/api/marketStatus",
        "exchange_session_state",
        DataTrust.OFFICIAL,
        "intraday",
        "Official NSE market-session state, trade date and index summary for operational labelling.",
        "STRUCTURED_OFFICIAL_COOKIE_API_LIVE_VERIFIED_2026_08_10",
        True,
        6,
        "Operational context only; never a stock signal, Consensus vote or Screener score term.",
    ),
    SourceDescriptor(
        "rupeevest_mf_flows",
        "RupeeVest Monthly Mutual-Fund Stock Flows",
        "https://www.rupeevest.com/Mutual-Fund-Holdings",
        "mutual_fund_stock_flow_context",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "monthly",
        "Public stock-level monthly mutual-fund buy/sell aggregates joined through RupeeVest's explicit symbol map.",
        "STRUCTURED_PUBLIC_JSON_ROUTES_LIVE_VERIFIED_2026_08_10",
        True,
        1440,
        "Third-party aggregate; informational and zero-score. It does not replace official AMFI disclosures.",
    ),
    SourceDescriptor(
        "amfi_monthly_aum",
        "AMFI Monthly Category AUM",
        "https://www.amfiindia.com/research-information/amfi-monthly",
        "mutual_fund_aggregate_context",
        DataTrust.OFFICIAL,
        "monthly",
        "Official category-level scheme count, folios, flows and assets under management for delayed mutual-fund context.",
        "STRUCTURED_OFFICIAL_MONTHLY_WORKBOOK_FETCHER_READY_2026_08_11",
        True,
        1440,
        "Monthly aggregate context only; cannot prove live stock buying and never becomes a Consensus voter or Screener score term.",
    ),
    SourceDescriptor(
        "crisil_ratings",
        "CRISIL Latest Rating Rationales",
        "https://www.crisilratings.com/content/crisilratings/en/home/our-business/ratings/rating-rationale/_jcr_content/wrapper_100_par/ratingresultlisting.results.json",
        "credit_rating_action",
        DataTrust.OFFICIAL,
        "event_based",
        "Official company rating-rationale actions and publication dates for stock-level research context.",
        "STRUCTURED_OFFICIAL_JSON_LIVE_VERIFIED_2026_08_10",
        True,
        96,
        "Company codes are not exchange tickers; no fuzzy symbol mapping. Informational only and never a Consensus vote or Screener score term.",
    ),
    SourceDescriptor(
        "icra_ratings",
        "ICRA Latest Rating Rationales",
        "https://www.icra.in/Rating/AllRatingRationales?Keyword=",
        "credit_rating_action",
        DataTrust.OFFICIAL,
        "event_based",
        "Official ICRA company rating-rationale actions and publication dates.",
        "STRUCTURED_OFFICIAL_CSRF_HTML_LIVE_VERIFIED_2026_08_10",
        True,
        96,
        "Company names are preserved unmapped; informational only and never a Consensus vote or Screener score term.",
    ),
    SourceDescriptor(
        "care_ratings",
        "CARE Latest Rating Rationales",
        "https://www.careratings.com/find-ratings",
        "credit_rating_action",
        DataTrust.OFFICIAL,
        "event_based",
        "Official CARE company rating-rationale publications and PDF links.",
        "STRUCTURED_OFFICIAL_PAGE_JSON_LIVE_VERIFIED_2026_08_10",
        True,
        96,
        "Encrypted CARE company IDs are preserved; no fuzzy ticker mapping. Informational only and zero-score.",
    ),
    SourceDescriptor(
        "lme_warehouse_stocks",
        "LME Price And Warehouse Context (Westmetall Fallback)",
        "https://www.westmetall.com/en/markdaten.php?action=table&field=LME_Cu_cash",
        "mcx_global_base_metals",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "daily",
        "Delayed cash, three-month price and aggregate warehouse-stock context for six LME base metals.",
        "STRUCTURED_THIRD_PARTY_FALLBACK_READY_2026_08_11",
        True,
        96,
        "Third-party delayed fallback, not an official LME artifact. Same-day detailed LME reports are licensed; this source is informational and zero-score.",
    ),
    SourceDescriptor(
        "eia_steo_opec_supply",
        "EIA STEO OPEC And OPEC+ Supply",
        "https://www.eia.gov/outlooks/steo/outlook.php",
        "global_oil_supply_context",
        DataTrust.OFFICIAL,
        "monthly",
        "Official monthly OPEC and OPEC+ petroleum-supply history and forecast context from the STEO Excel workbook.",
        "STRUCTURED_OFFICIAL_EXCEL_FETCHER_READY_2026_08_11",
        True,
        1440,
        "Supply/production is never relabelled as a quota; informational only and never a Consensus vote or Screener score term.",
    ),
    SourceDescriptor(
        "opec_production_adjustment",
        "OPEC+ Production Adjustment Releases",
        "https://www.opec.org/pr-detail/604-16-june-2026.html",
        "global_oil_policy_context",
        DataTrust.OFFICIAL,
        "monthly",
        "Official aggregate production-adjustment amount, effective month and participating-country context.",
        "STRUCTURED_OFFICIAL_RELEASE_FETCHER_READY_2026_08_11",
        True,
        1440,
        "Country quota values are not inferred from images or prose; informational only and never a Consensus vote or Screener score term.",
    ),
    SourceDescriptor(
        "bse_financial_results_xbrl",
        "BSE Financial Results XBRL Filing Index",
        "https://api.bseindia.com/BseIndiaAPI/api/Corp_FinanceResult_ng_new/w?SCRIP_CD=&FlagDur=4&HFQ=&ISUBGROUP_CODE=&segment=C",
        "corporate_financial_filing_index",
        DataTrust.OFFICIAL,
        "event_based",
        "Official market-wide BSE financial-result filing index with dated inline-XBRL detail links.",
        "STRUCTURED_OFFICIAL_INDEX_LIVE_VERIFIED_2026_08_11",
        True,
        96,
        "Filing discovery only until each linked inline-XBRL detail is hash-archived and context-parsed; informational and zero-score.",
    ),
    SourceDescriptor(
        "bse_shareholding_pattern",
        "BSE Shareholding Pattern Filing Index",
        "https://api.bseindia.com/BseIndiaAPI/api/Corp_Shareholding_ng/w?scripcode=&flag=4&indtype=",
        "corporate_shareholding_filing_index",
        DataTrust.OFFICIAL,
        "event_based",
        "Official market-wide BSE shareholding-pattern filing index with dated XBRL detail links.",
        "STRUCTURED_OFFICIAL_INDEX_LIVE_VERIFIED_2026_08_11",
        True,
        96,
        "No promoter/public percentage is inferred from index metadata; informational and zero-score.",
    ),
    SourceDescriptor(
        "rbi_tbill_yield",
        "RBI Treasury-Bill Auction Yields",
        "https://www.rbi.org.in/scripts/BS_PressReleaseDisplay.aspx",
        "risk_free_rate_context",
        DataTrust.OFFICIAL,
        "weekly",
        "Official latest 91/182/364-day Treasury-bill cut-off and weighted-average auction yields.",
        "STRUCTURED_OFFICIAL_DISCOVERY_LIVE_VERIFIED_2026_08_11",
        True,
        240,
        "Weekly auction result, not a live market rate; retain the dated last-good result and never relabel fetched time as auction date.",
    ),
    SourceDescriptor(
        "mcx_delivery_reports",
        "MCX Delivery Reports",
        "https://www.mcxindia.com/market-operations/clearing-settlement/delivery-reports",
        "mcx_delivery_pressure",
        DataTrust.OFFICIAL,
        "daily",
        "Contract delivery details, hedger intent and pay-in/pay-out pressure near expiry.",
        "RAW_INDEX_ARCHIVED_2026_07_17_EXCEL_PARSER_PENDING",
        True,
        48,
        "The public delivery-report page can be archived as research context, but linked Excel discovery and structured delivery-pressure parsing are still pending. Market summary and turnover are not substitutes.",
    ),
    SourceDescriptor(
        "fred_real_yield_10y",
        "FRED 10-Year Real Interest Rate",
        "https://fred.stlouisfed.org/series/DFII10",
        "mcx_global_gold",
        DataTrust.OFFICIAL,
        "daily",
        "Delayed US real-yield context for gold regime analysis.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_07_13",
        True,
        120,
        "Macro context only; it cannot prove intraday gold flow or independently unlock READY.",
    ),
    SourceDescriptor(
        "fred_broad_dollar_index",
        "FRED Broad Dollar Index",
        "https://fred.stlouisfed.org/series/DTWEXBGS",
        "mcx_global_gold",
        DataTrust.OFFICIAL,
        "daily",
        "Delayed broad-dollar context for commodity regime analysis.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_07_13",
        True,
        120,
        "Macro context only; publication lag and missing observations must remain explicit.",
    ),
    SourceDescriptor(
        "eia_weekly_petroleum_stocks",
        "EIA Weekly Petroleum Stocks",
        "https://www.eia.gov/petroleum/supply/weekly/index.php",
        "mcx_global_crude",
        DataTrust.OFFICIAL,
        "weekly",
        "Official US crude, gasoline and distillate inventory context for MCX crude.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_07_13",
        True,
        240,
        "Weekly delayed context only; release surprise requires a separate point-in-time expectation source.",
    ),
    SourceDescriptor(
        "cftc_cot",
        "CFTC Commitments of Traders",
        "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm",
        "mcx_global_positioning",
        DataTrust.OFFICIAL,
        "weekly",
        "Official Producer/Merchant, Swap Dealer, Managed Money, Other Reportable, and Non-reportable positioning.",
        "STRUCTURED_PARSER_BUILT_LIVE_ARTIFACT_VERIFIED_2026_07_11",
        True,
        192,
        "Friday release reflects Tuesday positions; stale after major events.",
    ),
    SourceDescriptor(
        "bse_sast",
        "BSE SAST Disclosures",
        "https://www.bseindia.com/corporates/SAST.aspx",
        "smart_money_ownership",
        DataTrust.OFFICIAL,
        "daily",
        "Official substantial-acquisition and takeover disclosure context.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_14",
        True,
        48,
        "Raw BSE API rows are archived, but symbol, event-date, revision, and ownership normalization must pass before G12 use.",
    ),
    SourceDescriptor(
        "bse_bulk_deals",
        "BSE Bulk Deals",
        "https://www.bseindia.com/markets/equity/EQReports/bulk_deals.aspx",
        "smart_money_deals",
        DataTrust.OFFICIAL,
        "daily",
        "Official named bulk-deal buyer, seller, quantity, and price evidence.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_14",
        True,
        48,
        "Raw rows cannot create sponsor proof until scrip mapping, data date, revisions, and deal-side semantics are normalized.",
    ),
    SourceDescriptor(
        "bse_block_deals",
        "BSE Block Deals",
        "https://www.bseindia.com/markets/equity/EQReports/block_deals",
        "smart_money_deals",
        DataTrust.OFFICIAL,
        "daily",
        "Official named block-deal buyer, seller, quantity, and price evidence.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_14",
        True,
        48,
        "A valid empty window is not a failure; non-empty rows still require scrip, date, side, and revision normalization before G12 use.",
    ),
    SourceDescriptor(
        "mcx_option_chain",
        "MCX Commodity Option Chain",
        "https://www.mcxindia.com/market-data/option-chain",
        "mcx_derivatives_context",
        DataTrust.OFFICIAL,
        "intraday",
        "Official public option-chain snapshot for commodity OI, volume, and IV research context.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_14",
        True,
        2,
        "Public snapshots are delayed/research-only and cannot replace the broker or licensed live feed required for execution READY.",
    ),
    SourceDescriptor(
        "mcx_market_watch",
        "MCX Market Watch",
        "https://www.mcxindia.com/market-data/market-watch",
        "mcx_price_volume_context",
        DataTrust.OFFICIAL,
        "intraday",
        "Official public MCX market-watch snapshot for contract discovery and research context.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_14",
        True,
        2,
        "This runtime URL is outside the original 211 inventory and remains research-only until contract identity, timestamps, and licensed execution prices are reconciled.",
    ),
    SourceDescriptor(
        "sge_benchmark_gold",
        "Shanghai Gold Exchange Benchmark Price",
        "https://en.sge.com.cn/h5_data_BenchmarkPrice",
        "mcx_global_gold",
        DataTrust.OFFICIAL,
        "daily",
        "Official Shanghai AM/PM benchmark history for delayed China gold-market context.",
        "STRUCTURED_PARSER_BUILT_LIVE_VERIFIED_2026_08_01",
        True,
        72,
        "Benchmark history is delayed context, not a live SGE physical-premium feed and not an independent MCX entry trigger.",
    ),
    SourceDescriptor(
        "baker_hughes_na_rig_count",
        "Baker Hughes North America Rig Count",
        "https://bakerhughesrigcount.gcs-web.com/rig-count-overview",
        "mcx_global_crude",
        DataTrust.OFFICIAL,
        "weekly",
        "Official North America rig-count workbook for delayed crude supply context.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_14",
        True,
        240,
        "The workbook is archived and hash-verified, but sheet/date/unit normalization is required before regime scoring.",
    ),
    SourceDescriptor(
        "usda_wasde",
        "USDA WASDE Report",
        "https://www.usda.gov/about-usda/general-information/staff-offices/office-chief-economist/commodity-markets/wasde-report",
        "agri_regime",
        DataTrust.OFFICIAL,
        "monthly",
        "Official global crop supply and ending-stock context for agri, fertilizer, sugar, oilseed and rural-demand themes.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_15",
        True,
        960,
        "Workbook rows are delayed macro/agri context only until sheet extraction, commodity mapping and report date are verified.",
    ),
    SourceDescriptor(
        "dgcis_trade_data",
        "DGCI&S / TRADESTAT Commodity Trade",
        "https://tradestat.commerce.gov.in/eidb/commodity_wise_all_countries_import",
        "india_trade_flow",
        DataTrust.OFFICIAL,
        "monthly",
        "Commodity import/export context for gold, oil, chemicals, refiners and rural or consumer-demand proxies.",
        "STRUCTURED_PARSER_PHASE3_MULTISTEP",
        True,
        960,
        "Multi-step CSRF form fetch; layout may change; keep last good on failure.",
    ),
    SourceDescriptor(
        "imd_rainfall_timeseries",
        "IMD Rainfall Time Series",
        "https://mausam.imd.gov.in/imd_latest/contents/rainfall_time_series.php",
        "monsoon_regime",
        DataTrust.OFFICIAL,
        "daily",
        "Rainfall and monsoon deviation context for fertilizer, agrochem, sugar, rural FMCG and irrigation-linked stocks.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_15",
        True,
        72,
        "District/subdivision table parsing is pending; until then it is visible research context only.",
    ),
    SourceDescriptor(
        "des_crop_estimates",
        "DES Advance Crop Estimates",
        "https://desagri.gov.in/statistics-type/advance-estimates/",
        "crop_supply",
        DataTrust.OFFICIAL,
        "event_based",
        "Advance crop estimate and production/acreage context for agriculture-linked sector risk.",
        "FETCH_FAILED_2026_07_15",
        True,
        2160,
        "The direct page failed local TLS verification; do not use until a stable official PDF/artifact contract is captured.",
    ),
    SourceDescriptor(
        "shfe_weekly_stock",
        "SHFE Weekly Stock Report",
        "https://www.shfe.com.cn/data/tradedata/future/weeklystock/",
        "china_metals_inventory",
        DataTrust.OFFICIAL,
        "weekly",
        "China exchange inventory context for copper, aluminium, zinc and base-metal regime.",
        "FETCH_FAILED_2026_07_15",
        True,
        240,
        "The tested dated .dat path returned 404; keep as resolver-pending until current date/path discovery is fixture-tested.",
    ),
    SourceDescriptor(
        "china_nbs_indicator",
        "China NBS Indicator API",
        "https://data.stats.gov.cn/english/easyquery.htm",
        "china_macro_regime",
        DataTrust.OFFICIAL,
        "monthly",
        "China manufacturing and PMI-style context for metals, chemicals and global cyclicals.",
        "FETCH_BLOCKED_2026_07_15",
        True,
        960,
        "The endpoint returned 403 from this environment; indicator mapping and access stability remain pending.",
    ),
    SourceDescriptor(
        "mcx_future_prices",
        "MCX Futures Prices",
        "https://www.mcxindia.com/backpage.aspx/GetFuturePrice",
        "mcx_distortion_guard",
        DataTrust.OFFICIAL,
        "daily",
        "MCX futures price context for abnormal price and expiry-distortion veto checks.",
        "FETCH_BLOCKED_2026_07_15",
        True,
        48,
        "MCX session seed returned 403; use no futures-price veto until a stable contract is verified.",
    ),
    SourceDescriptor(
        "mcx_trading_holidays",
        "MCX Trading Holidays",
        "https://www.mcxindia.com/backpage.aspx/GetTradingHoliday",
        "mcx_session_guard",
        DataTrust.OFFICIAL,
        "monthly",
        "MCX session guard to avoid stale scans on closed commodity-market days.",
        "FETCH_BLOCKED_2026_07_15",
        True,
        1080,
        "MCX session seed returned 403; do not infer holidays from stale or failed responses.",
    ),
    SourceDescriptor(
        "mcx_circulars",
        "MCX Circulars",
        "https://www.mcxindia.com/backpage.aspx/GetCircular",
        "mcx_rule_change",
        DataTrust.OFFICIAL,
        "daily",
        "Margin, lot-size, expiry, delivery and contract rule-change alerts.",
        "FETCH_BLOCKED_2026_07_15",
        True,
        72,
        "MCX session seed returned 403; no rule-change alert may be generated without a fresh circular artifact.",
    ),
    SourceDescriptor(
        "fbil_usdinr_reference",
        "FBIL USD/INR Reference Rate",
        "https://www.fbil.org.in/",
        "fx_parity",
        DataTrust.OFFICIAL,
        "daily",
        "USD/INR reference rate for MCX gold parity and currency-leg checks.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_15",
        True,
        48,
        "HTML is archived; a dated USD/INR row parser is required before parity calculations.",
    ),
    SourceDescriptor(
        "bse_xbrl_announcements",
        "BSE XBRL Announcements",
        "https://api.bseindia.com/BseIndiaAPI/api/AnnGetData/w",
        "material_event",
        DataTrust.OFFICIAL,
        "intraday",
        "BSE structured material-event and XBRL announcement discovery by category and scrip.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_15",
        True,
        24,
        "Event taxonomy, scrip mapping and duplicate/revision handling are required before G12 use.",
    ),
    SourceDescriptor(
        "nse_xbrl_taxonomy",
        "NSE XBRL Taxonomy",
        "https://www.nseindia.com/companies-listing/corporate-filings-xbrl",
        "disclosure_schema",
        DataTrust.OFFICIAL,
        "event_based",
        "NSE XBRL schema/taxonomy reference for corporate filing parser correctness.",
        "FETCH_FAILED_2026_07_15",
        True,
        2160,
        "The tested page returned 404; use only after the current taxonomy ZIP/page URL is discovered and fixture-tested.",
    ),
    SourceDescriptor(
        "nse_pit_annual",
        "NSE Annual PIT Window",
        "https://www.nseindia.com/api/corporates-pit",
        "insider_history",
        DataTrust.OFFICIAL,
        "on_demand",
        "Historical PIT behavior context for promoter, KMP and insider activity scoring.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_15",
        True,
        744,
        "Annual history is delayed behavior context; current PIT and price acceptance still control live evidence.",
    ),
    SourceDescriptor(
        "mca_company_master_data",
        "MCA Company Master Data",
        "https://data.gov.in/catalog/company-master-data",
        "company_identity_risk",
        DataTrust.OFFICIAL,
        "monthly",
        "CIN, company status and charges-discovery context from MCA open-data catalog.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_15",
        True,
        2160,
        "Catalog page is archived; a specific resource CSV/API must be selected and parsed before use.",
    ),
    SourceDescriptor(
        "cdsl_fpi_fortnightly",
        "CDSL FPI Fortnightly Publication",
        "https://www.cdslindia.com/Publications/ForeignPortInvestor.html",
        "fpi_flow_context",
        DataTrust.OFFICIAL,
        "fortnightly",
        "CDSL FPI publication context for depository-confirmed foreign portfolio flow.",
        "STRUCTURED_PARSER_EXISTING",
        True,
        480,
        "Structured parser available; fortnightly sector AUC when publication files resolve.",
    ),
    SourceDescriptor(
        "rbi_fpi_caution",
        "RBI FPI Caution / Breach Monitoring",
        "https://www.rbi.org.in/Scripts/BS_FiiUSer.aspx",
        "fpi_limit_headroom",
        DataTrust.OFFICIAL,
        "daily",
        "Foreign ownership headroom and caution/breach list for FPI demand constraints.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_15",
        True,
        72,
        "Table parser and source-date validation are pending; use only as visible risk context.",
    ),
    SourceDescriptor(
        "msei_fii_dii",
        "MSEI FII/DII Activity",
        "https://www.msei.in/downloads/equity-reports/fii-dii-activities",
        "institutional_flow_crosscheck",
        DataTrust.OFFICIAL,
        "daily",
        "Third-exchange FII/DII activity cross-check for combined institutional-flow context.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_15",
        True,
        48,
        "Download resolver and CSV/XLS parser are pending; NSE aggregate remains the active cash-flow source.",
    ),
    SourceDescriptor(
        "cftc_release_schedule",
        "CFTC COT Release Schedule",
        "https://www.cftc.gov/MarketReports/CommitmentsofTraders/ReleaseSchedule/index.htm",
        "cot_release_guard",
        DataTrust.OFFICIAL,
        "event_based",
        "COT release schedule for commodity positioning freshness and blackout windows.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_15",
        True,
        2160,
        "Schedule context only; it does not replace the structured CFTC position parser.",
    ),
    SourceDescriptor(
        "eia_petroleum_schedule",
        "EIA Petroleum Status Report Schedule",
        "https://www.eia.gov/petroleum/supply/weekly/schedule.php",
        "crude_event_blackout",
        DataTrust.OFFICIAL,
        "event_based",
        "EIA release schedule for crude blackout windows around weekly petroleum reports.",
        "RAW_ARCHIVE_CONNECTED_SCHEMA_PENDING_2026_07_15",
        True,
        2160,
        "Schedule parser pending; crude signals still require EIA metrics and price/OI confirmation.",
    ),
    SourceDescriptor(
        "yfinance",
        "yfinance OHLCV",
        "https://query1.finance.yahoo.com/",
        "temporary_ohlcv",
        DataTrust.UNOFFICIAL_TEMP,
        "on_demand",
        "Temporary OHLCV while official feed/broker is absent.",
        "IMPLEMENTED",
        False,
        24,
        "Not official trading truth; rate-limited and schema can change.",
    ),
    SourceDescriptor(
        "nsepython",
        "nsepython Wrapper",
        "https://github.com/aeron7/nsepython",
        "unofficial_wrapper",
        DataTrust.UNOFFICIAL_WRAPPER,
        "on_demand",
        "NSE public-site wrapper experiments.",
        "PARTIAL",
        False,
        168,
        "Depends on NSE website behavior.",
    ),
    SourceDescriptor(
        "nselib",
        "nselib Wrapper",
        "https://github.com/NSEDownload/nselib",
        "unofficial_wrapper",
        DataTrust.UNOFFICIAL_WRAPPER,
        "on_demand",
        "NSE EOD/report wrapper candidate.",
        "INSTALLED_EOD_SMOKE_VERIFIED",
        False,
        168,
        "nselib 2.5.1 is installed and its RELIANCE EOD path was smoke-tested; it remains an unofficial wrapper.",
    ),
    SourceDescriptor(
        "openchart_intraday",
        "openchart-style Intraday",
        "https://github.com/marketcalls/openchart",
        "unofficial_intraday",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "on_demand",
        "Temporary free intraday source candidate.",
        "INSTALLED_BUT_FAIL_CLOSED",
        False,
        24,
        "Source stability and schema must be verified before scanner use.",
    ),
    SourceDescriptor(
        "bse_fii_dii",
        "BSE FII/DII Category Turnover",
        "https://api.bseindia.com/BseIndiaAPI/api/CategoryTurnover/w",
        "institutional_flow",
        DataTrust.OFFICIAL,
        "daily",
        "BSE category-wise FII/DII cash turnover for aggregate regime context.",
        "OFFICIAL_API_STRUCTURED_PARSER",
        True,
        36,
        "Aggregate market-level flow only; not stock-level FII/MF attribution. "
        "Script-pack FIIDII/w and ParticipantWiseOI/w endpoints are dead HTML shells.",
    ),
    SourceDescriptor(
        "bse_participant_oi",
        "BSE Participant-wise Derivatives OI",
        "https://api.bseindia.com/BseIndiaAPI/api/DeriMarketDisclosureData_ng/w",
        "derivatives_regime",
        DataTrust.OFFICIAL,
        "daily",
        "BSE FII/DII/Pro/Client derivative positioning from market disclosures.",
        "OFFICIAL_API_STRUCTURED_PARSER",
        True,
        36,
        "Aggregate participant OI only; not stock-level FII buying. "
        "Pack ParticipantWiseOI/w is dead; live path is DeriMarketDisclosureData_ng.",
    ),
    SourceDescriptor(
        "screener_in_fii_holding_change",
        "Screener.in FII Holding Change",
        "https://www.screener.in/screens/343087/fii-buying/",
        "third_party_fii_holding_change",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "quarterly",
        "Third-party company-name FII hold % and change; usually no ticker.",
        "STRUCTURED_THIRD_PARTY_HTML_BUNDLE",
        True,
        168,
        "Not official daily FII tape. Names only; do not invent tickers. Informational and zero-score.",
    ),
    SourceDescriptor(
        "tickertape_fii_holding_change_3m",
        "Tickertape FII Holding Change 3M",
        "https://api.tickertape.in/screener/query",
        "third_party_fii_holding_change",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "quarterly",
        "Third-party ticker plus 3-month FII holding-percentage change.",
        "STRUCTURED_THIRD_PARTY_JSON_QUERY",
        True,
        168,
        "Not official daily FII tape. Informational and zero-score; never a Consensus vote.",
    ),
    SourceDescriptor(
        "dhan_fii_holding_change",
        "Dhan FII Holding Change",
        "https://ow-scanx-analytics.dhan.co/customscan/fetchdt",
        "third_party_fii_holding_change",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "quarterly",
        "Third-party ticker plus FII holding-change percent from Dhan customscan.",
        "STRUCTURED_THIRD_PARTY_JSON_SCAN",
        True,
        168,
        "Not official daily FII tape. Informational and zero-score; never a Consensus vote.",
    ),
    SourceDescriptor(
        "equitymaster_fii_buys_reference",
        "Equitymaster Institutional Buy Screen",
        "https://www.equitymaster.com/stock-screener/stocks-recently-bought-by-institutional-investors",
        "third_party_fii_holding_change",
        DataTrust.OPEN_SOURCE_UNOFFICIAL,
        "quarterly",
        "Third-party name-first institutional-buy HTML screen; Cloudflare may block.",
        "STRUCTURED_THIRD_PARTY_HTML_TABLE",
        True,
        168,
        "Not official daily FII tape. Name-first; do not invent tickers. Informational and zero-score.",
    ),
)


def source_catalog_records() -> list[SourceCatalogRecord]:
    return [
        SourceCatalogRecord(
            key=item.key,
            name=item.name,
            url=item.url,
            category=item.category,
            authority=item.authority,
            expectedFrequency=item.expected_frequency,
            decisionUse=item.decision_use,
            parserStatus=item.parser_status,
            freshnessRequired=item.freshness_required,
            staleAfterHours=item.stale_after_hours,
            limitation=item.limitation,
        )
        for item in SOURCE_CATALOG
    ]


SOURCE_KEY_ALIASES = {
    "nse_mwpl_ban": "nse_fno_ban",
    # Bundled WGC flows URL lives on the holdings registry job.
    "wgc_gold_etf_flows": "wgc_gold_etf_holdings",
}


def canonical_source_key(source_key: str) -> str:
    clean_key = source_key.strip().lower()
    return SOURCE_KEY_ALIASES.get(clean_key, clean_key)


def get_source_descriptor(source_key: str) -> SourceDescriptor | None:
    clean_key = canonical_source_key(source_key)
    for item in SOURCE_CATALOG:
        if item.key == clean_key:
            return item
    return None


def safe_source_key(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_.-]+", "_", value).strip("_") or "source"


def raw_source_dir(source_key: str) -> Path:
    path = storage.DB_PATH.parent / "raw_sources" / safe_source_key(source_key)
    path.mkdir(parents=True, exist_ok=True)
    return path


def hash_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def save_raw_snapshot(source_key: str, content_hash: str, content: bytes) -> Path:
    path = raw_source_dir(source_key) / f"{content_hash}.bin"
    if not path.exists():
        path.write_bytes(content)
    return path


def fetch_url(url: str, timeout_seconds: int = 15) -> tuple[int, dict[str, str], bytes]:
    request = Request(
        url,
        headers={
            "User-Agent": "TrendForgeLocalResearch/0.1 (+local freshness monitor)",
            "Accept": "text/html,application/xhtml+xml,application/xml,text/plain,*/*;q=0.8",
        },
    )
    with urlopen(request, timeout=timeout_seconds) as response:
        headers = {key.lower(): value for key, value in response.headers.items()}
        status = getattr(response, "status", 200)
        return int(status), headers, response.read()


def build_source_snapshot(
    descriptor: SourceDescriptor,
    *,
    status_code: int | None,
    content: bytes | None,
    headers: dict[str, str] | None,
    error: str | None = None,
    resolved_url: str | None = None,
    checked_at: str | None = None,
) -> SourceSnapshotRecord:
    checked = checked_at or datetime.now(timezone.utc).isoformat()
    latest = get_latest_source_snapshot(descriptor.key)
    previous_hash = latest.content_hash if latest else None
    content_hash = hash_bytes(content) if content is not None else None
    content_length = len(content) if content is not None else None
    selected_headers = headers or {}
    last_modified = selected_headers.get("last-modified")
    etag = selected_headers.get("etag")
    changed = bool(content_hash and previous_hash and content_hash != previous_hash)
    state: Literal["NEW", "UNCHANGED", "CHANGED", "STALE", "BROKEN", "SKIPPED"]
    if error:
        state = "BROKEN"
        raw_path = None
    elif content is None:
        state = "SKIPPED"
        raw_path = None
    else:
        assert content_hash is not None
        if previous_hash is None:
            state = "NEW"
        elif content_hash == previous_hash:
            state = "UNCHANGED"
        else:
            state = "CHANGED"
        raw_path = str(save_raw_snapshot(descriptor.key, content_hash, content))

    return SourceSnapshotRecord(
        sourceKey=descriptor.key,
        name=descriptor.name,
        url=resolved_url or descriptor.url,
        checkState=state,
        statusCode=status_code,
        contentHash=content_hash,
        contentLength=content_length,
        lastModified=last_modified,
        etag=etag,
        rawPath=raw_path,
        error=error,
        checkedAt=checked,
        previousHash=previous_hash,
        changed=changed or state == "NEW",
    )


def check_source(
    source_key: str,
    *,
    fetch: bool = True,
    timeout_seconds: int = 15,
) -> SourceSnapshotRecord:
    descriptor = get_source_descriptor(source_key)
    if descriptor is None:
        raise KeyError(f"Unknown source key: {source_key}")
    if not fetch:
        snapshot = build_source_snapshot(
            descriptor,
            status_code=None,
            content=None,
            headers=None,
            error=None,
        )
        return save_source_snapshot(snapshot)

    try:
        resolved = resolve_and_fetch_source(
            descriptor.key, descriptor.url, timeout_seconds=timeout_seconds
        )
        return _save_resolved_snapshot(descriptor, resolved)
    except HTTPError as exc:
        headers = (
            {key.lower(): value for key, value in exc.headers.items()}
            if exc.headers
            else {}
        )
        snapshot = build_source_snapshot(
            descriptor,
            status_code=exc.code,
            content=None,
            headers=headers,
            error=f"HTTP {exc.code}: {exc.reason}",
        )
    except (URLError, TimeoutError, OSError) as exc:
        snapshot = build_source_snapshot(
            descriptor,
            status_code=None,
            content=None,
            headers=None,
            error=str(exc),
        )
    return save_source_snapshot(snapshot)


def _save_resolved_snapshot(
    descriptor: SourceDescriptor, resolved: ResolvedFetch
) -> SourceSnapshotRecord:
    """Archive one resolver result under a source key.

    The helper also lets a multi-source run reuse the same PR ZIP bytes for
    bhavcopy, T2T and the PR market snapshot without creating a second fetch
    path or weakening each source's independent archive lineage.
    """
    try:
        save_source_fetch_attempts(
            descriptor.key,
            uuid4().hex,
            [attempt.as_dict() for attempt in resolved.attempts],
        )
        status_code, headers, content = (
            resolved.status_code,
            dict(resolved.headers),
            resolved.content,
        )
        headers["x-trendforge-resolver-state"] = resolved.resolver_state
        if status_code >= 400:
            snapshot = build_source_snapshot(
                descriptor,
                status_code=status_code,
                content=None,
                headers=headers,
                resolved_url=resolved.url,
                error=f"HTTP {status_code}",
            )
        else:
            snapshot = build_source_snapshot(
                descriptor,
                status_code=status_code,
                content=content,
                headers=headers,
                resolved_url=resolved.url,
            )
    except (OSError, ValueError) as exc:
        snapshot = build_source_snapshot(
            descriptor,
            status_code=None,
            content=None,
            headers=None,
            error=str(exc),
        )
    return save_source_snapshot(snapshot)


def check_sources(
    source_keys: list[str] | None = None,
    *,
    fetch: bool = True,
    timeout_seconds: int = 15,
) -> SourceMonitorSummary:
    selected = source_keys or [item.key for item in SOURCE_CATALOG]
    results: list[SourceSnapshotRecord] = []
    shared_pr_keys = {
        "nse_bhavcopy_eod",
        "nse_trade_to_trade",
        "nse_pr_market_snapshot",
    }
    requested_pr_keys = [key for key in selected if key in shared_pr_keys]
    handled: set[str] = set()
    if fetch and len(requested_pr_keys) > 1:
        anchor = get_source_descriptor("nse_trade_to_trade")
        assert anchor is not None
        try:
            resolved = resolve_and_fetch_source(
                anchor.key, anchor.url, timeout_seconds=timeout_seconds
            )
            if resolved.status_code < 400:
                for key in requested_pr_keys:
                    descriptor = get_source_descriptor(key)
                    assert descriptor is not None
                    results.append(_save_resolved_snapshot(descriptor, resolved))
                    handled.add(key)
            else:
                for key in requested_pr_keys:
                    if key == "nse_bhavcopy_eod":
                        continue
                    descriptor = get_source_descriptor(key)
                    assert descriptor is not None
                    results.append(_save_resolved_snapshot(descriptor, resolved))
                    handled.add(key)
        except (HTTPError, URLError, TimeoutError, OSError):
            # check_source will persist an ordinary BROKEN result for each key.
            pass
    for key in selected:
        if key not in handled:
            results.append(check_source(key, fetch=fetch, timeout_seconds=timeout_seconds))
    order = {key: index for index, key in enumerate(selected)}
    results.sort(key=lambda item: order.get(item.source_key, len(order)))
    return summarize_results(len(selected), results)


def summarize_results(
    total_sources: int, results: list[SourceSnapshotRecord]
) -> SourceMonitorSummary:
    return SourceMonitorSummary(
        totalSources=total_sources,
        checked=len(results),
        newCount=sum(1 for row in results if row.check_state == "NEW"),
        changedCount=sum(1 for row in results if row.check_state == "CHANGED"),
        unchangedCount=sum(1 for row in results if row.check_state == "UNCHANGED"),
        brokenCount=sum(1 for row in results if row.check_state == "BROKEN"),
        skippedCount=sum(1 for row in results if row.check_state == "SKIPPED"),
        results=results,
    )


def source_snapshot_history(
    source_key: str | None = None, limit: int = 100
) -> list[SourceSnapshotRecord]:
    return list_source_snapshots(source_key=source_key, limit=limit)
